### ISSUE TITLE
What are the differences between this and Papyros's qml-material?

### ISSUE THREAD

**Issue by NLKNguyen** [rschiang/material#4]
I found yours is easier to get started than this https://github.com/papyros/qml-material. I wonder what are the differences between the two?

**Comment by rschiang** [comment]
This project is actually pitched in [MOPCON 2014](http://mopcon.org/2014/) Lightning Talk, to demonstrate the capability of QML. It's mostly tailored for the example app, with usability prior to extensibility. I haven't noticed Papyros until recently, but they've done great works on formalizing components AFAIK.

Also, Papyros is GPL licensed, whilst Material is BSD. Hope you could find some good use of this project. :)
